/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-12-04 04:38:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class oho_005ffindPwd2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/SpringOhora/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectOhora/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1731460991358L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(' ');
      out.write(' ');
 String
contextPath = request.getContextPath(); String emailOrPhoneCheck = (String)
request.getAttribute("contactMethod"); System.out.println("emailOrPhoneCheck : "
+ emailOrPhoneCheck); String email = (String) request.getAttribute("email");
System.out.println("@@@@@@@@@@@@@@ : " + email); String phone =
(String)request.getAttribute("phone"); System.out.println("@@@@@@@@@@@@@@ : " +
phone); String userID = (String)request.getAttribute("userID");
System.out.println("@@@@@@@@@@@@@@ : " + userID); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>오호라 팀 프로젝트</title>\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"shortcut icon\"\r\n");
      out.write("      type=\"image/x-icon\"\r\n");
      out.write("      href=\"http://localhost/jspPro/images/SiSt.ico\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Libre+Baskerville|Noto+Sans+KR&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <meta name=\"google\" content=\"notranslate\" />\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      .container {\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        width: 1920px;\r\n");
      out.write("        height: 670px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .title {\r\n");
      out.write("        color: rgba(0, 0, 0, 1);\r\n");
      out.write("        width: 138.04px;\r\n");
      out.write("        height: 37px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: 811.84px;\r\n");
      out.write("        top: 130px;\r\n");
      out.write("        font-family: \"Libre Baskerville\", serif;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .description {\r\n");
      out.write("        color: rgba(119, 119, 119, 1);\r\n");
      out.write("        width: 496.52px;\r\n");
      out.write("        height: 35px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: 711.84px;\r\n");
      out.write("        top: 205px;\r\n");
      out.write("        font-family: \"Noto Sans KR\", sans-serif;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .form-container {\r\n");
      out.write("        width: 500px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: 710px;\r\n");
      out.write("        top: 261px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .label-container {\r\n");
      out.write("        background-color: rgba(241, 241, 241, 1);\r\n");
      out.write("        width: 160px;\r\n");
      out.write("        height: 34px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding-left: 10px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .label-text {\r\n");
      out.write("        color: rgba(0, 0, 0, 1);\r\n");
      out.write("        font-family: \"Noto Sans KR\", sans-serif;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .radio-group {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 5px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: 170px;\r\n");
      out.write("        top: 0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .radio-label {\r\n");
      out.write("        color: rgba(0, 0, 0, 1);\r\n");
      out.write("        font-family: \"Noto Sans KR\", sans-serif;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .input-field {\r\n");
      out.write("        width: 330px;\r\n");
      out.write("        height: 34px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: 170px;\r\n");
      out.write("        border: 1px solid rgba(221, 221, 221, 1);\r\n");
      out.write("        padding: 0 10px;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        font-family: \"Noto Sans KR\", sans-serif;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .button-container {\r\n");
      out.write("        width: 500px;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 250px;\r\n");
      out.write("        background-color: rgba(0, 0, 0, 1);\r\n");
      out.write("        border: 1px solid rgba(0, 0, 0, 1);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .button-container button {\r\n");
      out.write("        background-color: #000000;\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: rgba(255, 255, 255, 1);\r\n");
      out.write("        font-family: \"Noto Sans KR\", sans-serif;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .cancel-button-container {\r\n");
      out.write("        width: 500px;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 302px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .cancel-button {\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: rgba(0, 0, 0, 1);\r\n");
      out.write("        font-family: \"Noto Sans KR\", sans-serif;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #abcde {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #trueBtn {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #failBtn {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\"></div>\r\n");
      out.write("    <span class=\"title\">PASSWORD FIND</span>\r\n");
      out.write("    <span class=\"description\">본인확인 인증</span>\r\n");
      out.write("\r\n");
      out.write("    <form\r\n");
      out.write("      id=\"formUserID\"\r\n");
      out.write("      class=\"form-container\"\r\n");
      out.write("      method=\"post\"\r\n");
      out.write("      action=\"/findPwd3.htm\"\r\n");
      out.write("    >\r\n");
      out.write("      <!-- 본인확인 인증 라디오 버튼 -->\r\n");
      out.write("      <div class=\"label-container\" style=\"top: 10px\">\r\n");
      out.write("        <span class=\"label-text\">본인확인 인증</span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"radio-group\" style=\"top: 10px\">\r\n");
      out.write("        <input\r\n");
      out.write("          type=\"radio\"\r\n");
      out.write("          id=\"phone\"\r\n");
      out.write("          name=\"verification_method\"\r\n");
      out.write("          value=\"phone\"\r\n");
      out.write("        />\r\n");
      out.write("        <label for=\"phone\" class=\"radio-label\">휴대폰</label>\r\n");
      out.write("\r\n");
      out.write("        <input\r\n");
      out.write("          type=\"radio\"\r\n");
      out.write("          id=\"email\"\r\n");
      out.write("          name=\"verification_method\"\r\n");
      out.write("          value=\"email\"\r\n");
      out.write("        />\r\n");
      out.write("        <label for=\"email\" class=\"radio-label\">이메일</label>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- contact 입력란 -->\r\n");
      out.write("      <div class=\"label-container\" style=\"top: 55px\">\r\n");
      out.write("        ");
 if ( emailOrPhoneCheck.equals("phone") ) { 
      out.write("\r\n");
      out.write("        <span class=\"label-text\">휴대폰 번호</span>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("        <span class=\"label-text\">이메일</span>\r\n");
      out.write("        ");
 } // if else 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <input\r\n");
      out.write("        type=\"text\"\r\n");
      out.write("        class=\"input-field\"\r\n");
      out.write("        id=\"value\"\r\n");
      out.write("        style=\"top: 55px\"\r\n");
      out.write("        name=\"number\"\r\n");
      out.write("        value=\"\"\r\n");
      out.write("        readonly\r\n");
      out.write("      />\r\n");
      out.write("      \r\n");
      out.write("      <button\r\n");
      out.write("        type=\"button\"\r\n");
      out.write("        id=\"getCode\"\r\n");
      out.write("        class=\"input-field\"\r\n");
      out.write("        style=\"top: 55px; left: 510px; width: 100px; cursor: pointer\"\r\n");
      out.write("        onclick=\"getVerifyCode()\"\r\n");
      out.write("      >\r\n");
      out.write("        인증번호 받기\r\n");
      out.write("      </button>\r\n");
      out.write("      \r\n");
      out.write("      <!-- 인증번호 받기 -->\r\n");
      out.write("    <script>\r\n");
      out.write("	  function getVerifyCode() {\r\n");
      out.write("	    // AJAX 요청\r\n");
      out.write("	    $.ajax({\r\n");
      out.write("	      url: \"/ajax/getCode.ajax\", \r\n");
      out.write("	      type: \"GET\", \r\n");
      out.write("	      dataType: \"json\",\r\n");
      out.write("	      success: function (response) {\r\n");
      out.write("	        // 서버에서 받은 응답을 분기하여 처리\r\n");
      out.write("	        if (response == 1) {\r\n");
      out.write("	          // 인증번호 발급 성공\r\n");
      out.write("	          alert(\"인증번호가 발송되었습니다.\");\r\n");
      out.write("	        } else if (response == 0) {\r\n");
      out.write("	          // 인증번호 발급 실패\r\n");
      out.write("	          alert(\"인증번호 발송에 실패했습니다.\");\r\n");
      out.write("	        } else {\r\n");
      out.write("	          // 예기치 않은 응답 처리\r\n");
      out.write("	          alert(\"알 수 없는 오류가 발생했습니다.\");\r\n");
      out.write("	        }\r\n");
      out.write("	      },\r\n");
      out.write("	      error: function (xhr, status, error) {\r\n");
      out.write("	        console.error(\"에러 발생: \", error);\r\n");
      out.write("	        alert(\"인증번호를 받는 데 문제가 발생했습니다.\");\r\n");
      out.write("	      },\r\n");
      out.write("	    });\r\n");
      out.write("	  }\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("      <!-- 인증번호 입력란 -->\r\n");
      out.write("      <div class=\"label-container\" style=\"top: 115px\">\r\n");
      out.write("        <span class=\"label-text\">인증번호</span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 내가 입력한 값 -->\r\n");
      out.write("      <input\r\n");
      out.write("        type=\"text\"\r\n");
      out.write("        id=\"myCode\"\r\n");
      out.write("        class=\"input-field\"\r\n");
      out.write("        style=\"top: 115px\"\r\n");
      out.write("        name=\"myCode\"\r\n");
      out.write("        placeholder=\"인증번호를 입력하세요\"\r\n");
      out.write("      />\r\n");
      out.write("\r\n");
      out.write("      <button\r\n");
      out.write("        type=\"button\"\r\n");
      out.write("        id=\"checkCode\"\r\n");
      out.write("        class=\"input-field\"\r\n");
      out.write("        style=\"top: 115px; left: 510px; width: 100px; cursor: pointer\"\r\n");
      out.write("        onclick=\"checkVerifyCode()\"\r\n");
      out.write("      >\r\n");
      out.write("        인증번호 확인\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <!-- 안내 문구 -->\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"label-text\"\r\n");
      out.write("        style=\"position: absolute; top: 165px; left: 170px; font-size: 10px\"\r\n");
      out.write("      >\r\n");
      out.write("        1회 발송된 인증번호의 유효 시간은 3분이며,<br />\r\n");
      out.write("        1회 인증번호 발송 후 30초 이후에 재전송이 가능합니다.\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 확인 버튼 -->\r\n");
      out.write("      <div class=\"button-container\" id=\"trueBtn\">\r\n");
      out.write("        <button type=\"button\" class=\"button-text\" disabled>확인</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 취소 버튼 -->\r\n");
      out.write("      <div class=\"cancel-button-container\" id=\"failBtn\">\r\n");
      out.write("        <button type=\"button\" class=\"cancel-button\">취소</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <input type=\"hidden\" name=\"userID\" value=\"");
      out.print( userID );
      out.write("\" />\r\n");
      out.write("      <input\r\n");
      out.write("        type=\"hidden\"\r\n");
      out.write("        name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("        value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("      />\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      // 인증번호 확인 함수\r\n");
      out.write("      // 인증번호 확인 함수\r\n");
      out.write("      function checkVerifyCode() {\r\n");
      out.write("        let myCode = $(\"#myCode\").val(); // 입력된 인증 코드 가져오기\r\n");
      out.write("        let authCode = $(\"#authCode\").val(); // 필요한 경우 authCode 값 가져오기\r\n");
      out.write("\r\n");
      out.write("        // 입력된 인증 코드가 비어있지 않으면 서버로 요청 보내기\r\n");
      out.write("        if (myCode == \"\") {\r\n");
      out.write("          alert(\"인증번호가 비어있습니다.\"); // 비어있는 경우 처리\r\n");
      out.write("          return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 인증번호 확인을 위한 AJAX 요청\r\n");
      out.write("        $.ajax({\r\n");
      out.write("          url: \"/ajax/checkCode.ajax\",\r\n");
      out.write("          type: \"GET\",\r\n");
      out.write("          data: {\r\n");
      out.write("            myCode: myCode,\r\n");
      out.write("            authCode: authCode,\r\n");
      out.write("          },\r\n");
      out.write("          dataType: \"json\",\r\n");
      out.write("          success: function (response) {\r\n");
      out.write("            if (response == 1) {\r\n");
      out.write("              alert(\"인증번호 확인이 완료되었습니다.\");\r\n");
      out.write("              // 인증번호가 맞으면 확인 버튼을 활성화\r\n");
      out.write("              $(\"#trueBtn .button-text\").prop(\"disabled\", false);\r\n");
      out.write("            } else if (response == 0) {\r\n");
      out.write("              alert(\"유효하지 않은 인증번호입니다.\");\r\n");
      out.write("              // 인증번호가 틀리면 확인 버튼을 비활성화\r\n");
      out.write("              $(\"#trueBtn .button-text\").prop(\"disabled\", true);\r\n");
      out.write("            }\r\n");
      out.write("          },\r\n");
      out.write("          error: function (xhr, status, error) {\r\n");
      out.write("            console.error(\"에러 발생: \", error);\r\n");
      out.write("            alert(\"인증번호 확인에 문제가 발생했습니다.\");\r\n");
      out.write("          },\r\n");
      out.write("        });\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // 확인 버튼 클릭 시 폼 제출\r\n");
      out.write("      $(\"#trueBtn\").on(\"click\", function () {\r\n");
      out.write("        // 인증번호가 입력되었고 확인 버튼이 활성화된 경우에만 폼 제출\r\n");
      out.write("        if (\r\n");
      out.write("          $(\"#texttext\").val() != \"\" &&\r\n");
      out.write("          !$(\"#trueBtn .button-text\").prop(\"disabled\")\r\n");
      out.write("        ) {\r\n");
      out.write("          alert(\"본인인증이 완료되었습니다.\"); // 성공 메시지 띄우기\r\n");
      out.write("          $(\"#formUserID\").submit(); // 인증이 완료된 후 폼 제출\r\n");
      out.write("        } else {\r\n");
      out.write("          alert(\"인증번호를 확인해주세요.\"); // 인증번호가 입력되지 않았거나 실패한 경우\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 이메일 또는 폰에 맞게 라디오 버튼 활성화 및 비활성화 / 값 넣기 -->\r\n");
      out.write("    <script>\r\n");
      out.write("      var emailOrPhoneCheck = \"");
      out.print( emailOrPhoneCheck != null ? emailOrPhoneCheck : "" );
      out.write("\";\r\n");
      out.write("      if (emailOrPhoneCheck === \"email\") {\r\n");
      out.write("          $(\"#email\").prop(\"checked\", true);\r\n");
      out.write("          $(\"#phone\").prop(\"disabled\", true);\r\n");
      out.write("          $(\"#value\").val(\"");
      out.print( email );
      out.write("\");\r\n");
      out.write("      } else {\r\n");
      out.write("          $(\"#phone\").prop(\"checked\", true);\r\n");
      out.write("          $(\"#email\").prop(\"disabled\", true);\r\n");
      out.write("          $(\"#value\").val(\"");
      out.print( phone );
      out.write("\");\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
