/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-12-04 04:03:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class oho_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/SpringOhora/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectOhora/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1731460991358L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 String contextPath =
request.getContextPath(); 
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>오호라 팀 프로젝트</title>\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"shortcut icon\"\r\n");
      out.write("      type=\"image/x-icon\"\r\n");
      out.write("      href=\"http://localhost/jspPro/images/SiSt.ico\"\r\n");
      out.write("    />\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <meta name=\"google\" content=\"notranslate\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/projectOhora/resources/cdn-main/login.css\" />\r\n");
      out.write("    <script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("      span.material-symbols-outlined {\r\n");
      out.write("        vertical-align: text-bottom;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  ");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\" style=\"padding-top: 156px !important\">\r\n");
      out.write("      <div id=\"container\">\r\n");
      out.write("        <div id=\"contents\">\r\n");
      out.write("          <div id=\"SMS_login_warp\" class=\"login_container SP_layoutFix\">\r\n");
      out.write("            <form\r\n");
      out.write("              id=\"loginForm\"\r\n");
      out.write("              name=\"\"\r\n");
      out.write("              action=\"");
      out.print( contextPath );
      out.write("/login\"\r\n");
      out.write("              method=\"post\"\r\n");
      out.write("              target=\"_self\"\r\n");
      out.write("            >\r\n");
      out.write("              <!-- 이것 때문에 post 가 안됨 -->\r\n");
      out.write("              <!-- enctype=\"multipart/form-data\" -->\r\n");
      out.write("\r\n");
      out.write("              <input\r\n");
      out.write("                id=\"returnUrl\"\r\n");
      out.write("                name=\"returnUrl\"\r\n");
      out.write("                value=\"https://www.ohora.kr/\"\r\n");
      out.write("                type=\"hidden\"\r\n");
      out.write("              />\r\n");
      out.write("              <input\r\n");
      out.write("                id=\"forbidIpUrl\"\r\n");
      out.write("                name=\"forbidIpUrl\"\r\n");
      out.write("                value=\"/\"\r\n");
      out.write("                type=\"hidden\"\r\n");
      out.write("              />\r\n");
      out.write("              <input\r\n");
      out.write("                id=\"certificationUrl\"\r\n");
      out.write("                name=\"certificationUrl\"\r\n");
      out.write("                value=\"/intro/adult_certification.html\"\r\n");
      out.write("                type=\"hidden\"\r\n");
      out.write("              />\r\n");
      out.write("              <input\r\n");
      out.write("                id=\"sIsSnsCheckid\"\r\n");
      out.write("                name=\"sIsSnsCheckid\"\r\n");
      out.write("                value=\"\"\r\n");
      out.write("                type=\"hidden\"\r\n");
      out.write("              />\r\n");
      out.write("              <input id=\"sProvider\" name=\"sProvider\" value=\"\" type=\"hidden\" />\r\n");
      out.write("              <div id=\"\" class=\"xans-element- xans-member xans-member-login\">\r\n");
      out.write("                <!--\r\n");
      out.write("         $defaultReturnUrl = /index.html\r\n");
      out.write("      -->\r\n");
      out.write("                <!--주문조회-->\r\n");
      out.write("                <div class=\"loginWrap\">\r\n");
      out.write("                  <div class=\"tab eTab displaynone\">\r\n");
      out.write("                    <div class=\"KJtabBox\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li class=\"selected\">\r\n");
      out.write("                          <a href=\"#member\" id=\"login_order_user\">회원</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#noMember\" id=\"login_order_notuser\"\r\n");
      out.write("                            >비회원</a\r\n");
      out.write("                          >\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div\r\n");
      out.write("                    df-banner-code=\"login-banner\"\r\n");
      out.write("                    class=\"loginBnr displaynone df-bannermanager df-bannermanager-login-banner\"\r\n");
      out.write("                  >\r\n");
      out.write("                    <div df-banner-clone=\"\">\r\n");
      out.write("                      <a href=\"#none\"\r\n");
      out.write("                        ><img\r\n");
      out.write("                          src=\"/web/upload/NNEditor/20201221/538e6d1a805ea2edea743e38fdb35f8f.jpg\"\r\n");
      out.write("                          alt=\"login_banner_img\"\r\n");
      out.write("                      /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"titleArea\">\r\n");
      out.write("                    <p>\r\n");
      out.write("                      회원가입 후 첫 구매시, <br /><strong\r\n");
      out.write("                        >오호라 젤 램프를 선물</strong\r\n");
      out.write("                      >로 드립니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>(18,000원 상당)</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <fieldset>\r\n");
      out.write("                    <div class=\"formBox\">\r\n");
      out.write("                      <div class=\"form login\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <span class=\"\">아이디 입력</span>\r\n");
      out.write("                          <input\r\n");
      out.write("                            id=\"member_id\"\r\n");
      out.write("                            name=\"username\"\r\n");
      out.write("                            fw-filter=\"isFill\"\r\n");
      out.write("                            fw-label=\"아이디\"\r\n");
      out.write("                            fw-msg=\"\"\r\n");
      out.write("                            class=\"inputTypeText\"\r\n");
      out.write("                            placeholder=\"\"\r\n");
      out.write("                            value=\"asdf\"\r\n");
      out.write("                            type=\"text\"\r\n");
      out.write("                          />\r\n");
      out.write("                          <span class=\"reset_id\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 확인 필요 -->\r\n");
      out.write("                        <div id=\"aaaaaa\"></div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <span class=\"\">비밀번호 입력</span>\r\n");
      out.write("                          <input\r\n");
      out.write("                            id=\"member_passwd\"\r\n");
      out.write("                            name=\"password\"\r\n");
      out.write("                            fw-filter=\"isFill&amp;isMin[4]&amp;isMax[16]\"\r\n");
      out.write("                            fw-label=\"패스워드\"\r\n");
      out.write("                            fw-msg=\"\"\r\n");
      out.write("                            autocomplete=\"off\"\r\n");
      out.write("                            value=\"asdf1234\"\r\n");
      out.write("                            type=\"password\"\r\n");
      out.write("                            placeholder=\"\"\r\n");
      out.write("                          />\r\n");
      out.write("                          <span class=\"show_pw\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"option\">\r\n");
      out.write("                        <span class=\"auto\"></span>\r\n");
      out.write("                        <span class=\"save\"></span>\r\n");
      out.write("                        <span class=\"ssl\"\r\n");
      out.write("                          ><img\r\n");
      out.write("                            src=\"https://www.ohora.kr/web/upload/common/save_login.png\"\r\n");
      out.write("                            alt=\"보안접속\"\r\n");
      out.write("                          /><em>보안접속</em></span\r\n");
      out.write("                        >\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"btnArea type1\">\r\n");
      out.write("                        <button\r\n");
      out.write("                          type=\"button\"\r\n");
      out.write("                          class=\"btnSubmit SMSlogin_btnTD\"\r\n");
      out.write("                          style=\"cursor: pointer\"\r\n");
      out.write("                          onclick=\"loginClick();\"\r\n");
      out.write("                          id=\"loginBtn\"\r\n");
      out.write("                        >\r\n");
      out.write("                          로그인\r\n");
      out.write("                        </button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"btnArea type1\">\r\n");
      out.write("                        <a\r\n");
      out.write("                          href=\"#none\"\r\n");
      out.write("                          class=\"btnKakao sns_login_Btn\"\r\n");
      out.write("                          onclick=\"MemberAction.kakaosyncLogin('9ae31018e6a3df11adb5d4dfa9cc9d37')\"\r\n");
      out.write("                          id=\"a\"\r\n");
      out.write("                          ><span>카카오로 3초 만에 시작하기</span></a\r\n");
      out.write("                        >\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"btnArea type1 sns\">\r\n");
      out.write("                        <!-- 6.0클래스 icon -->\r\n");
      out.write("                        <a\r\n");
      out.write("                          href=\"#none\"\r\n");
      out.write("                          class=\"btnNaver sns_login_Btn\"\r\n");
      out.write("                          onclick=\"MemberAction.snsLogin('naver', '%2F')\"\r\n");
      out.write("                          ><span>네이버로 로그인</span></a\r\n");
      out.write("                        >\r\n");
      out.write("                        <a\r\n");
      out.write("                          href=\"#none\"\r\n");
      out.write("                          class=\"btnFacebook sns_login_Btn\"\r\n");
      out.write("                          onclick=\"MemberAction.snsLogin('facebook', '%2F')\"\r\n");
      out.write("                          ><span>페이스북으로 로그인</span></a\r\n");
      out.write("                        >\r\n");
      out.write("                        <a\r\n");
      out.write("                          href=\"#none\"\r\n");
      out.write("                          class=\"apple_login btnApple\"\r\n");
      out.write("                          onclick=\"MemberAction.snsLogin('apple', '%2F')\"\r\n");
      out.write("                          ><span>Apple로 로그인</span></a\r\n");
      out.write("                        >\r\n");
      out.write("                        <!--\r\n");
      out.write("                        <a href=\"#none\" class=\"btnGoogle displaynone\" onclick=\"\"><span>구글 로그인</span></a>\r\n");
      out.write("                        <a href=\"#none\" class=\"btnLine displaynone\" onclick=\"\"><span>라인 로그인</span></a>\r\n");
      out.write("                        -->\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"btnArea typeLogin\">\r\n");
      out.write("                        <a\r\n");
      out.write("                          href=\"");
      out.print( contextPath );
      out.write("/goFindId1.htm\"\r\n");
      out.write("                          class=\"btnLogin SMS_login_id SMSloginID_btnTD\"\r\n");
      out.write("                          id=\"aa\"\r\n");
      out.write("                          ><b class=\"SMS_icon\"></b>아이디 찾기</a\r\n");
      out.write("                        >\r\n");
      out.write("                        <a\r\n");
      out.write("                          href=\"");
      out.print( contextPath );
      out.write("/goPasswd1.htm\"\r\n");
      out.write("                          class=\"btnLogin SMS_login_pw SMSloginPW_btnTD\"\r\n");
      out.write("                          id=\"aaa\"\r\n");
      out.write("                          ><b class=\"SMS_icon\"></b>비밀번호 찾기</a\r\n");
      out.write("                        >\r\n");
      out.write("                        <a\r\n");
      out.write("                          href=\"");
      out.print( contextPath );
      out.write("/ohora.do?ordercheck=ordercheck_nolog\"\r\n");
      out.write("                          class=\"btnLogin SMS_login_id_join SMSjoin_btnTD\"\r\n");
      out.write("                          id=\"aaaa\"\r\n");
      out.write("                          ><b class=\"SMS_icon\"></b>비회원 주문조회</a\r\n");
      out.write("                        >\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"btnJoin btnArea type1 join_btn\">\r\n");
      out.write("                        <a\r\n");
      out.write("                          href=\"/goJoin1.htm\"\r\n");
      out.write("                          class=\"btnEm SMSjoin_btnTD wh\"\r\n");
      out.write("                          id=\"aaaaa\"\r\n");
      out.write("                          >회원가입 후 혜택받기</a\r\n");
      out.write("                        >\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"btnArea type1 guest_order displaynone\">\r\n");
      out.write("                        <a class=\"btnEm SMSnomem_btnBuyTD wh\">비회원 구매</a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"nonmember_pop_container\">\r\n");
      out.write("                        <div class=\"nonmember_pop\">\r\n");
      out.write("                          <div class=\"nonmember_con\">\r\n");
      out.write("                            <p class=\"fontB\">\r\n");
      out.write("                              비회원으로 구매하시면<br /><strong\r\n");
      out.write("                                >18,000원 상당의 젤램프 증정</strong\r\n");
      out.write("                              >이 불가합니다.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <span>구매하시겠습니까?</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"nonmember_btn_wrap\">\r\n");
      out.write("                            <a\r\n");
      out.write("                              href=\"/member/join_intro.html\"\r\n");
      out.write("                              class=\"kakao_regist\"\r\n");
      out.write("                              >젤램프 받고 구매</a\r\n");
      out.write("                            >\r\n");
      out.write("                            <a href=\"\" onclick=\"\" class=\"nonmember_buy\"\r\n");
      out.write("                              >바로 구매</a\r\n");
      out.write("                            >\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </fieldset>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--//주문조회-->\r\n");
      out.write("              </div>\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"hidden\"\r\n");
      out.write("                name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("              />\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 해당 스크립트 삭제에 유의 부탁드리며, 스냅 솔루션의 스크립트입니다. -->\r\n");
      out.write("          <!---- snappush  start contact mail: support@snapvi.co.kr --->\r\n");
      out.write("          <div id=\"spm_page_type\" style=\"display: none\">sq_login_page</div>\r\n");
      out.write("          <script\r\n");
      out.write("            async=\"\"\r\n");
      out.write("            type=\"text/javascript\"\r\n");
      out.write("            src=\"//cdn.snapfit.co.kr/js/spm_f_common.js\"\r\n");
      out.write("            charset=\"utf-8\"\r\n");
      out.write("          ></script>\r\n");
      out.write("          <div id=\"spm_banner_main\"></div>\r\n");
      out.write("          <!---- snappush  end -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("  <!-- 로그인 클릭 submit -->\r\n");
      out.write("  <script>\r\n");
      out.write("    function loginClick() {\r\n");
      out.write("      // alert(\"test\");\r\n");
      out.write("      $(\"#loginForm\").submit();\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("      if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.change}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" === \"success\") {\r\n");
      out.write("        alert(\"비밀번호가 성공적으로 변경되었습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("      if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.change}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" === \"fail\") {\r\n");
      out.write("        alert(\"비밀번호 변경이 실패했습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("  <!-- 로그인 실패 후 alert 창 띄우기 -->\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("      if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" === \"fail\") {\r\n");
      out.write("        alert(\"아이디 또는 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("  <!-- 이거 추가 갱신 된거다.  -->\r\n");
      out.write("  <!-- 비밀번호 변경 성공 시 alert 창 띄우기 -->\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("      if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.changeLogin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" === \"goChangeLogin\") {\r\n");
      out.write("        alert(\"비밀번호가 성공적으로 변경되었습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("  <!-- 이거 추가 갱신 된거다.  -->\r\n");
      out.write("  <!-- loginCheckFilter 로 로그인이 안될 시 alert 창 띄우기 -->\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("      if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.loginCheck}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" === \"fail\") {\r\n");
      out.write("        alert(\"로그인 후 이용 가능한 페이지입니다.\");\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 로그인 enter 처리 -->\r\n");
      out.write("  <script>\r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("      // ID와 비밀번호 입력 필드에 keypress 이벤트 추가\r\n");
      out.write("      $(\"#member_id, #member_passwd\").on(\"keypress\", function(e) {\r\n");
      out.write("          // 엔터키의 keyCode는 13\r\n");
      out.write("          if (e.keyCode === 13) {\r\n");
      out.write("              // 기본 이벤트(form submit) 방지\r\n");
      out.write("              e.preventDefault();\r\n");
      out.write("              // 로그인 함수 호출\r\n");
      out.write("              loginClick();\r\n");
      out.write("          }\r\n");
      out.write("      });\r\n");
      out.write("  });\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
