/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-12-04 04:03:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/SpringOhora/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectOhora/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar", Long.valueOf(1731461761808L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/SpringOhora/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectOhora/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1731460991358L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/SpringOhora/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectOhora/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1532606274000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


Integer userId = (Integer) session.getAttribute("userId");
Integer pdtCount = (Integer) session.getAttribute("pdtCount"); // 스프링 수정

// 값 확인
System.out.println("header userId : " + userId);
System.out.println("header pdtCount : " + pdtCount); // 스프링 수정

String contextPath = request.getContextPath();

   // 세션에서 로그인 상태 확인
boolean isLoggedIn = (session.getAttribute("userId") != null);

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라 팀 프로젝트</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("  <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      type=\"text/css\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("  href=\"https://fonts.googleapis.com/css?family=Libre Baskerville\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<div class=\"SP_topBanner\" style=\"display: block\">\r\n");
      out.write("      <div class=\"SP_layoutMin\">\r\n");
      out.write("        <div class=\"SP_topBn_inr\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"xans-element- xans-layout xans-layout-statelogoff\">\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"slide_banner_top slick-initialized slick-slider\"\r\n");
      out.write("            id=\"sltop_ban\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"slick-list draggable\">\r\n");
      out.write("              <div\r\n");
      out.write("                class=\"slick-track\"\r\n");
      out.write("                style=\"\r\n");
      out.write("                  opacity: 1;\r\n");
      out.write("                  width: 1200px;\r\n");
      out.write("                  transform: translate3d(0px, 0px, 0px);\r\n");
      out.write("                \"\r\n");
      out.write("              >\r\n");
      out.write("                <div\r\n");
      out.write("                  class=\"slick-slide slick-current slick-active\"\r\n");
      out.write("                  data-slick-index=\"0\"\r\n");
      out.write("                  aria-hidden=\"false\"\r\n");
      out.write("                  style=\"width: 1200px\"\r\n");
      out.write("                  tabindex=\"0\"\r\n");
      out.write("                >\r\n");
      out.write("                  <a\r\n");
      out.write("                    href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=eventnew\"\r\n");
      out.write("                    tabindex=\"0\"\r\n");
      out.write("                    style=\"display: block\"\r\n");
      out.write("                    ><img\r\n");
      out.write("                      src=\"https://ohora.kr/optimize/images/pc/common/PC_header_lamp2.webp\"\r\n");
      out.write("                      style=\"width: 100%; display: block\"\r\n");
      out.write("                  /></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 회원 -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"fix_position\" class=\"modify ham_modify\">\r\n");
      out.write("      <div id=\"SMS_fixed_wrap\" class=\"SMS_fixed_wrap\">\r\n");
      out.write("        <div class=\"SP_top_wrap\">\r\n");
      out.write("          <div class=\"layout_Top\">\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"xans-element- xans-layout xans-layout-statelogoff SP_gnb_inr\"\r\n");
      out.write("            >\r\n");
      out.write("            \r\n");
      out.write("            <!-- 인증되지 않은 사용자 (로그인 해야함) -->\r\n");
      out.write("     		");
      //  sec:authorize
      org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
      boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
      try {
        _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
        _jspx_th_sec_005fauthorize_005f0.setParent(null);
        // /WEB-INF/views/inc/header.jsp(97,7) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous()");
        int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
        if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("<a href=\"");
          out.print( contextPath );
          out.write("/goJoin1.htm\"><span class=\"title\">회원가입</span></a>|\r\n");
          out.write("                <a href=\"");
          out.print( contextPath );
          out.write("/login.htm\" class=\"log\"><span class=\"title\">로그인</span></a>\r\n");
          out.write("            ");
        }
        if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
        _jspx_th_sec_005fauthorize_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
      }
      out.write("<!-- 인증된 사용자 (로그인한 사용자) -->\r\n");
      out.write("            ");
      //  sec:authorize
      org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
      boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
      try {
        _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
        _jspx_th_sec_005fauthorize_005f1.setParent(null);
        // /WEB-INF/views/inc/header.jsp(105,12) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated() and !hasRole('ROLE_ADMIN')");
        int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
        if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("<a href=\"");
          out.print( contextPath );
          out.write("/user/mypage.htm\"><span class=\"title\">마이페이지</span></a>|\r\n");
          out.write("            	\r\n");
          out.write("            	 <a class=\"log\" style=\"cursor: pointer;\"><span class=\"title\">로그아웃</span></a>\r\n");
          out.write("				<form id=\"logoutForm\" action=\"/logout.htm\" method=\"post\" style=\"display: none;\">\r\n");
          out.write("				    <input type=\"hidden\" name=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("				</form>\r\n");
          out.write("				\r\n");
          out.write("				<script>\r\n");
          out.write("					 $(document).ready(function(){\r\n");
          out.write("						 $('.log').click(function(e){\r\n");
          out.write("							  e.preventDefault(); // 기본 동작(페이지 이동)을 막음\r\n");
          out.write("							      $('#logoutForm').submit(); // form 제출\r\n");
          out.write("							     });\r\n");
          out.write("						  });\r\n");
          out.write("				</script>\r\n");
          out.write("            ");
        }
        if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
        _jspx_th_sec_005fauthorize_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
      }
      out.write("<!-- 관리자 사용자 (ROLE_ADMIN) -->\r\n");
      out.write("             ");
      //  sec:authorize
      org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
      boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
      try {
        _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
        _jspx_th_sec_005fauthorize_005f2.setParent(null);
        // /WEB-INF/views/inc/header.jsp(127,13) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sec_005fauthorize_005f2.setAccess("hasRole('ROLE_ADMIN')");
        int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
        if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("<a href=\"");
          out.print( contextPath );
          out.write("/auth.htm\"><span class=\"title\">관리자페이지</span></a>|\r\n");
          out.write("            	\r\n");
          out.write("            	 <a class=\"log\" style=\"cursor: pointer;\"><span class=\"title\">로그아웃</span></a>\r\n");
          out.write("				<form id=\"logoutForm\" action=\"/logout.htm\" method=\"post\" style=\"display: none;\">\r\n");
          out.write("				    <input type=\"hidden\" name=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("				</form>\r\n");
          out.write("								\r\n");
          out.write("				 <script>\r\n");
          out.write("					 $(document).ready(function(){\r\n");
          out.write("						 $('.log').click(function(e){\r\n");
          out.write("							  e.preventDefault(); // 기본 동작(페이지 이동)을 막음\r\n");
          out.write("							      $('#logoutForm').submit(); // form 제출\r\n");
          out.write("							     });\r\n");
          out.write("						  });\r\n");
          out.write("				</script>\r\n");
          out.write("            ");
        }
        if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
        _jspx_th_sec_005fauthorize_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
      }
      out.write("</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"SMS_fixed_inner\">\r\n");
      out.write("          <div class=\"xans-element- xans-layout xans-layout-logotop fixed_logo\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"/main.htm\"\r\n");
      out.write("              style=\"display: block; text-align: center; margin-top: 30px\"\r\n");
      out.write("            >\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"https://ohora.kr/web/upload/logo/ohora_BI_logotype_w.png\"\r\n");
      out.write("               \r\n");
      out.write("              />\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 헤더 주메뉴 -->\r\n");
      out.write("          <div class=\"gnb_menu_container\">\r\n");
      out.write("            <ul class=\"gnb_menu_wrap menu_1ul\">\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/prdList.htm?sort=new\" style=\"color:black !important;\">new</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/prdList.htm?sort=sales\" style=\"color:black !important;\">best</a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"eng_font\">\r\n");
      out.write("                <a href=\"/prdList.htm\" style=\"color:black !important;\">product</a>\r\n");
      out.write("\r\n");
      out.write("                <!-- 마우스 오버 시 나오는 영역(product) -->\r\n");
      out.write("                <ul class=\"menu_2ul\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"><span>네일</span></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"><span>페디</span></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=#><span>커스텀</span></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"><span>케어 &amp; 툴</span></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- //마우스 오버 시 나오는 영역(product) -->\r\n");
      out.write("              </li>\r\n");
      out.write("			  \r\n");
      out.write("			  ");
      if (_jspx_meth_sec_005fauthorize_005f3(_jspx_page_context))
        return;
      if (_jspx_meth_sec_005fauthorize_005f4(_jspx_page_context))
        return;
      if (_jspx_meth_sec_005fauthorize_005f5(_jspx_page_context))
        return;
      out.write("<script>\r\n");
      out.write("              	$(\"#outletBtn\").on(\"click\", function(){\r\n");
      out.write("              		alert(\"로그인 시 이용 가능한 페이지입니다.\");\r\n");
      out.write("              	});\r\n");
      out.write("              </script>\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"eng_font\"><a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=event\" style=\"color:black !important;\">event</a></li>\r\n");
      out.write("              <li class=\"eng_font\">\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?howto=howto\" style=\"color:black !important;\">how to</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- //헤더 주메뉴 -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"icon_wrap\">\r\n");
      out.write("            <div class=\"small_icon search_fixed_btn\"></div>\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"xans-element- xans-layout xans-layout-orderbasketcount small_icon m_cart common_cart\"\r\n");
      out.write("            >\r\n");
      out.write("              <!-- 고정 값 0 을 어떻게 동적으로 바꾸는가 -->\r\n");
      out.write("             \r\n");
      out.write("             ");
      if (_jspx_meth_sec_005fauthorize_005f6(_jspx_page_context))
        return;
      //  sec:authorize
      org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f7 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
      boolean _jspx_th_sec_005fauthorize_005f7_reused = false;
      try {
        _jspx_th_sec_005fauthorize_005f7.setPageContext(_jspx_page_context);
        _jspx_th_sec_005fauthorize_005f7.setParent(null);
        // /WEB-INF/views/inc/header.jsp(242,12) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sec_005fauthorize_005f7.setAccess("isAuthenticated()");
        int _jspx_eval_sec_005fauthorize_005f7 = _jspx_th_sec_005fauthorize_005f7.doStartTag();
        if (_jspx_eval_sec_005fauthorize_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("<form action=\"");
          out.print(contextPath );
          out.write("/userCart/select.htm\"  method=\"get\" id=\"CartForm\">\r\n");
          out.write("                     <a href=\"#\" id=\"goCart\">\r\n");
          out.write("                         <b class=\"count EC-Layout-Basket-count\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdtCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b> <!-- ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" -->\r\n");
          out.write("                     </a>\r\n");
          out.write("                     ");
          out.write("</form>\r\n");
          out.write("            ");
        }
        if (_jspx_th_sec_005fauthorize_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f7);
        _jspx_th_sec_005fauthorize_005f7_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f7, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f7_reused);
      }
      out.write("</div>\r\n");
      out.write("            <div class=\"small_icon m_menu\"><a class=\"SMS_menu\"></a></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    <!-- 검색 -->\r\n");
      out.write("    <div class=\"hd_search_container\" style=\"overflow: hidden; display: none\">\r\n");
      out.write("      <div class=\"SP_search_wrap\">\r\n");
      out.write("        <div class=\"SP_utilListSearch_inner\">\r\n");
      out.write("          <form\r\n");
      out.write("            id=\"searchBarForm\"\r\n");
      out.write("            name=\"\"\r\n");
      out.write("            action=\"/prdList.htm\"\r\n");
      out.write("            method=\"get\"\r\n");
      out.write("            target=\"_self\"\r\n");
      out.write("            enctype=\"multipart/form-data\"\r\n");
      out.write("          >\r\n");
      out.write("            <input id=\"banner_action\" name=\"banner_action\" value=\"\" type=\"hidden\" />\r\n");
      out.write("            <div class=\"xans-element- xans-layout xans-layout-searchheader\">\r\n");
      out.write("          \r\n");
      out.write("              <fieldset>\r\n");
      out.write("                <legend style=\"display: none\">검색</legend>\r\n");
      out.write("                <input\r\n");
      out.write("                  id=\"keyword\"\r\n");
      out.write("                  name=\"keyword\"\r\n");
      out.write("                  fw-filter=\"\"\r\n");
      out.write("                  fw-label=\"검색어\"\r\n");
      out.write("                  fw-msg=\"\"\r\n");
      out.write("                  class=\"inputTypeText\"\r\n");
      out.write("                  placeholder=\"\"\r\n");
      out.write("                  onkeyup=\"SEARCH_HASHTAG.getHashtag($(this)); \"\r\n");
      out.write("                  autocomplete=\"off\"\r\n");
      out.write("                  onmousedown=\"SEARCH_BANNER.clickSearchForm(this)\"\r\n");
      out.write("                  value=\"\"\r\n");
      out.write("                  type=\"text\"\r\n");
      out.write("                /><button\r\n");
      out.write("                  type=\"button\"\r\n");
      out.write("                  class=\"SP_srh_submit_btn\"\r\n");
      out.write("                  onclick=\"SEARCH_BANNER.submitSearchBanner(this); return false;\"\r\n");
      out.write("                >\r\n");
      out.write("                  <span class=\"SP_cm_icon SP_black_search_icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("              </fieldset>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <!--------------- 검색 키워드 --------------->\r\n");
      out.write("        <div class=\"SP_utilListKeyword_inner\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"/projectOhora/product/list.do?sort=outlet\">#OUTLET 입장하기</a></li>\r\n");
      out.write("            <li><a href=\"/projectOhora/product/list.do\">#BEST 디자인 추천</a></li>\r\n");
      out.write("            <li><a href=\"a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=event6\">#첫구매 젤램프 증정</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--------------- 검색 키워드 --------------->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 더보기 -->\r\n");
      out.write("    <div class=\"hd_cate_container\" style=\"overflow: hidden; display: none\">\r\n");
      out.write("      <div class=\"SP_category_wrap\" style=\"margin-top: 172px;\">\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("      \r\n");
      out.write("          <div class=\"cate_wrap first\">\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?sort=new\">\r\n");
      out.write("                <span>new</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do?sort=new\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do?sort=new\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-top:50px\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?sort=sales\">\r\n");
      out.write("                <span>best</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a href=\"/projectOhora/product/list.do?catno=1&pageNum=1\">\r\n");
      out.write("                <span>네일</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a href=\"/projectOhora/product/list.do?catno=2&pageNum=1\">\r\n");
      out.write("                <span>페디</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"cate_wrap first\">\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?catno=1&currentPage=1\">\r\n");
      out.write("                <span>nail</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do?catno=1&currentPage=1\">\r\n");
      out.write("                <span>젤스트립</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-top:80px\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?catno=2&currentPage=1\">\r\n");
      out.write("                <span>pedi</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do?catno=2&currentPage=1\">\r\n");
      out.write("                <span>젤스트립</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"cate_wrap first\">\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?sort=outlet\">\r\n");
      out.write("                <span>outlet</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <span></span>\r\n");
      out.write("\r\n");
      out.write("              <span></span>\r\n");
      out.write("\r\n");
      out.write("              <span></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-top:105px\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>custom</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-top:38px\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?catno=3&currentPage=1\">\r\n");
      out.write("                <span>care &amp; tool</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!--------- 첫번째 줄 메뉴(신제품 출시 관련 수정 영역) --------->\r\n");
      out.write("          <style>\r\n");
      out.write("          \r\n");
      out.write("          </style>\r\n");
      out.write("\r\n");
      out.write("          <!------- 두번째 줄 메뉴 ------>\r\n");
      out.write("          <div class=\"cate_wrap second\">\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-left: 35px; margin-bottom: 42px;\">\r\n");
      out.write("              <a class=\"big_ eng_font\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=event\">\r\n");
      out.write("                <span>event</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-left: 35px;  margin-bottom: 42px;\">\r\n");
      out.write("              <a\r\n");
      out.write("                class=\"big_ eng_font\"\r\n");
      out.write("                href=\"#none\"\r\n");
      out.write("              >\r\n");
      out.write("                <span>review</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-left: 35px;\">\r\n");
      out.write("              <a class=\"big_ eng_font\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?about=about\">\r\n");
      out.write("                <span style=\"margin-top: 10px;\">brand</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?about=about\">\r\n");
      out.write("                <span>about</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?membership=membership\">\r\n");
      out.write("                <span>membership</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?magazine=magazine\">\r\n");
      out.write("                <span>magazine</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"#empty\">\r\n");
      out.write("                <span>collaboration</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!------ 두번째 줄 메뉴 ------>\r\n");
      out.write("          <!------ 세번째 줄 메뉴 ------>\r\n");
      out.write("          <div class=\"cate_wrap crew\">\r\n");
      out.write("  <!--오호라 크루 추천-->\r\n");
      out.write("  <div\r\n");
      out.write("    class=\"common_reco_section recommend_crew slider-container slider-container-initialized slider-container-horizontal load-complete\"\r\n");
      out.write("     style=\"margin-left: 100px\"\r\n");
      out.write("  >\r\n");
      out.write("    <h3>오호라 크루 추천</h3>\r\n");
      out.write("    <div\r\n");
      out.write("      df-banner-code=\"common-recommend\"\r\n");
      out.write("      class=\"recommend_banner_wrap slider-wrapper df-bannermanager df-bannermanager-common-recommend\"\r\n");
      out.write("      style=\"width: 260px; height: 231px\"\r\n");
      out.write("    >\r\n");
      out.write("      <div\r\n");
      out.write("        df-banner-clone=\"\"\r\n");
      out.write("        class=\"SP_eventBn_li slider-slide slider-slide-prev\"\r\n");
      out.write("      >\r\n");
      out.write("        <a href=\"#empty\"\r\n");
      out.write("          ><div class=\"imgBox\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"https://ohora.kr/web/upload/appfiles/ZaReJam3QiELznoZeGGkMG/94fad6d6474acf635b9c771591480a7c.png\"\r\n");
      out.write("              alt=\"페이코 상시 12% 할인\"\r\n");
      out.write("            />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"txtBox\">페이코 상시 12% 할인</div></a\r\n");
      out.write("        >\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 스와이퍼 스크롤 -->\r\n");
      out.write("    <div class=\"slider-scrollbar\">\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"slider-scrollbar-drag\"\r\n");
      out.write("        style=\"transition-duration: 0ms; transform: translate3d(0px, 0px, 0px); width: 80px;\"\r\n");
      out.write("      ></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <span\r\n");
      out.write("      class=\"slider-notification\"\r\n");
      out.write("      aria-live=\"assertive\"\r\n");
      out.write("      aria-atomic=\"true\"\r\n");
      out.write("    ></span>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--// 오호라 크루 추천-->\r\n");
      out.write("  <div class=\"third_cate\" style=\"margin-left: 108px; margin-top: 65px;\">\r\n");
      out.write("    <a href=\"https://oe9lp.channel.io/home\"><span style=\"font-size:13px ; color:black !important;\" >CS Center &nbsp;|</span></a>\r\n");
      out.write("    <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?notice=notice\"><span style=\"font-size:13px ; color:black !important;\"> &nbsp; Notice &nbsp;|</span></a>\r\n");
      out.write("    <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?FAQ=FAQ\"><span style=\"font-size:13px ; color:black !important;\"> &nbsp; FAQ &nbsp;|</span></a>\r\n");
      out.write("    <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?howto=howto\"><span style=\"font-size:13px ; color:black !important;\"> &nbsp; How to</span></a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div> <!-- sticky 적용을 위한 태그-->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  <!-- 슬라이더 초기화 코드 -->\r\n");
      out.write("   <!-- 슬라이더 초기화 코드 -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function () {\r\n");
      out.write("        $(\".slide_banner_top\").slick({\r\n");
      out.write("          infinite: true,\r\n");
      out.write("          speed: 300,\r\n");
      out.write("          slidesToShow: 1,\r\n");
      out.write("          dots: false,\r\n");
      out.write("          arrows: false,\r\n");
      out.write("          autoplay: true,\r\n");
      out.write("          autoplaySpeed: 3000,\r\n");
      out.write("          swipe: true,\r\n");
      out.write("          pauseOnHover: false,\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("      $(\"#goCart\").on(\"click\", function(event){\r\n");
      out.write("         // alert(\"test\");\r\n");
      out.write("         event.preventDefault();\r\n");
      out.write("         $(\"#CartForm\").submit();\r\n");
      out.write("      });\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("        const searchContainer = $('.hd_search_container');\r\n");
      out.write("        const cateContainer = $('.hd_cate_container');\r\n");
      out.write("\r\n");
      out.write("        searchContainer.hide();\r\n");
      out.write("        cateContainer.hide();\r\n");
      out.write("\r\n");
      out.write("        // 검색 버튼 클릭 시\r\n");
      out.write("        $('.small_icon.search_fixed_btn').on('click', function() {\r\n");
      out.write("          if (!searchContainer.is(':visible')) {\r\n");
      out.write("            cateContainer.stop(true, true).fadeOut(300, function() {\r\n");
      out.write("              searchContainer.stop(true, true).slideDown(500).animate({ opacity: 1 }, { duration: 10 });\r\n");
      out.write("              $('#keyword').focus();\r\n");
      out.write("            });\r\n");
      out.write("          } else {\r\n");
      out.write("            searchContainer.stop(true, true).slideUp(500).animate({ opacity: 0 }, { duration: 10 });\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 더보기 버튼 클릭 시\r\n");
      out.write("        $('.SMS_menu').on('click', function() {\r\n");
      out.write("          if (!cateContainer.is(':visible')) {\r\n");
      out.write("            searchContainer.stop(true, true).fadeOut(300, function() {\r\n");
      out.write("              cateContainer.stop(true, true).slideDown(500).animate({ opacity: 1 }, { duration: 10 });\r\n");
      out.write("              $('#keyword').focus();\r\n");
      out.write("            });\r\n");
      out.write("          } else {\r\n");
      out.write("            cateContainer.stop(true, true).slideUp(500).animate({ opacity: 0 }, { duration: 10 });\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("<script>\r\n");
      out.write("const NonMemberCartManager = {\r\n");
      out.write("    getBasketCookie() {\r\n");
      out.write("        const cookie = document.cookie\r\n");
      out.write("            .split('; ')\r\n");
      out.write("            .find(row => row.startsWith('basketItems='));\r\n");
      out.write("        return cookie ? cookie.split('=')[1] : null;\r\n");
      out.write("    },\r\n");
      out.write("    \r\n");
      out.write("    updateCount() {\r\n");
      out.write("        try {\r\n");
      out.write("            const cookieValue = this.getBasketCookie();\r\n");
      out.write("            const countElement = document.querySelector('#nouser');\r\n");
      out.write("            \r\n");
      out.write("            if (!countElement) return;\r\n");
      out.write("\r\n");
      out.write("            if (cookieValue) {\r\n");
      out.write("                const basketItems = cookieValue.split(',');\r\n");
      out.write("                countElement.textContent = basketItems.length;\r\n");
      out.write("            } else {\r\n");
      out.write("                countElement.textContent = '0';\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            console.error('장바구니 카운트 업데이트 중 오류:', error);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("     <!-- <script>\r\n");
      out.write("      function checkLogin(event) {\r\n");
      out.write("          // 로그인 여부 확인\r\n");
      out.write("          if (!isLoggedIn) {\r\n");
      out.write("              // 로그인되지 않은 경우 경고창 표시 및 링크 이동 막기\r\n");
      out.write("              event.preventDefault(); // 기본 링크 이동 동작 취소\r\n");
      out.write("              alert(\"회원만 접근 가능합니다.\");\r\n");
      out.write("          }\r\n");
      out.write("          // 로그인된 경우 링크 이동 (기본 동작)\r\n");
      out.write("      }\r\n");
      out.write("   </script> -->\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/inc/header.jsp(178,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/prdList.htm?pageNum=1&categoryNumber=1");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/inc/header.jsp(181,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/prdList.htm?pageNum=1&categoryNumber=2");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/inc/header.jsp(187,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/prdList.htm?pageNum=1&categoryNumber=3");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f3 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f3_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f3.setParent(null);
      // /WEB-INF/views/inc/header.jsp(193,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f3.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f3 = _jspx_th_sec_005fauthorize_005f3.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("<li class=\"eng_font menu_1li submenu\">\r\n");
        out.write("	                <a href=\"/outlet.htm?pageNum=1\" style=\"color:black !important;\" onclick=\"checkLogin(event)\" id=\"outletBtn\">outlet</a>\r\n");
        out.write("	              </li>\r\n");
        out.write("              ");
      }
      if (_jspx_th_sec_005fauthorize_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f3);
      _jspx_th_sec_005fauthorize_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f3, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f4 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f4_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f4.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f4.setParent(null);
      // /WEB-INF/views/inc/header.jsp(198,14) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f4.setAccess("isAuthenticated() and !hasRole('ROLE_ADMIN')");
      int _jspx_eval_sec_005fauthorize_005f4 = _jspx_th_sec_005fauthorize_005f4.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("<li class=\"eng_font menu_1li submenu\">\r\n");
        out.write("	                <a href=\"/outlet.htm?pageNum=1\" style=\"color:black !important;\" onclick=\"checkLogin(event)\">outlet</a>\r\n");
        out.write("	              </li>\r\n");
        out.write("              ");
      }
      if (_jspx_th_sec_005fauthorize_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f4);
      _jspx_th_sec_005fauthorize_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f4, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f5 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f5_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f5.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f5.setParent(null);
      // /WEB-INF/views/inc/header.jsp(203,14) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f5.setAccess("hasRole('ROLE_ADMIN')");
      int _jspx_eval_sec_005fauthorize_005f5 = _jspx_th_sec_005fauthorize_005f5.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("<li class=\"eng_font menu_1li submenu\">\r\n");
        out.write("	                <a href=\"/outlet.htm?pageNum=1\" style=\"color:black !important;\" onclick=\"checkLogin(event)\">outlet</a>\r\n");
        out.write("	              </li>\r\n");
        out.write("              ");
      }
      if (_jspx_th_sec_005fauthorize_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f5);
      _jspx_th_sec_005fauthorize_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f5, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f6 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f6_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f6.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f6.setParent(null);
      // /WEB-INF/views/inc/header.jsp(229,13) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f6.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f6 = _jspx_th_sec_005fauthorize_005f6.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("<form action=\"/main.htm\" method=\"get\" id=\"CartForm\">\r\n");
        out.write("               <input type=\"hidden\" name=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("                     <a href=\"#\" id=\"goCart\">\r\n");
        out.write("                         <b class=\"count EC-Layout-Basket-count\" id=\"nouser\" >0</b>\r\n");
        out.write("                     </a>\r\n");
        out.write("                 </form>\r\n");
        out.write("                 <script>\r\n");
        out.write("                 window.addEventListener('load', () => {\r\n");
        out.write("                       NonMemberCartManager.updateCount();\r\n");
        out.write("                   });\r\n");
        out.write("                 </script>\r\n");
        out.write("            ");
      }
      if (_jspx_th_sec_005fauthorize_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f6);
      _jspx_th_sec_005fauthorize_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f6, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f6_reused);
    }
    return false;
  }
}
