/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-12-02 06:01:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class prdAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/SpringOhora/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectOhora/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1731460991358L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<form action=\"\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("		<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		\r\n");
      out.write("	    <table border=\"1\" style=\"border-collapse: collapse; width: 50%; margin: auto;\">\r\n");
      out.write("	        <thead>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	                <th colspan=\"2\" style=\"text-align: center; padding: 10px; background-color: #f2f2f2;\">상품 추가</th>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	        </thead>\r\n");
      out.write("	        <tbody>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	                <td style=\"padding: 10px; text-align: right;\">상품명:</td>\r\n");
      out.write("	                <td style=\"padding: 10px;\">\r\n");
      out.write("	                    <input type=\"text\" id=\"pdtName\" name=\"pdtName\" required style=\"width: 100%;\">\r\n");
      out.write("	                </td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	                <td style=\"padding: 10px; text-align: right;\">메인 카테고리 ID:</td>\r\n");
      out.write("	                <td style=\"padding: 10px;\">\r\n");
      out.write("	                    <select id=\"catId\" name=\"catId\">\r\n");
      out.write("	                    	<option value=\"\" disabled selected>상품의 메인 카테고리를 선택하세요</option>\r\n");
      out.write("	                    	<option value=\"1\">네일</option>\r\n");
      out.write("                            <option value=\"2\">페디</option>\r\n");
      out.write("                            <option value=\"3\">케어앤툴</option>\r\n");
      out.write("	                    </select>\r\n");
      out.write("	                </td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	                <td style=\"padding: 10px; text-align: right;\">상품 가격:</td>\r\n");
      out.write("	                <td style=\"padding: 10px;\">\r\n");
      out.write("	                    <input type=\"number\" id=\"pdtAmount\" name=\"pdtAmount\" style=\"width: 100%;\">\r\n");
      out.write("	                </td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	                <td style=\"padding: 10px; text-align: right;\">할인율:</td>\r\n");
      out.write("	                <td style=\"padding: 10px;\">\r\n");
      out.write("	                    <input type=\"number\" id=\"pdtDiscountRate\" name=\"pdtDiscountRate\" style=\"width: 100%;\">\r\n");
      out.write("	                </td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	                <td style=\"padding: 10px; text-align: right;\">재고량:</td>\r\n");
      out.write("	                <td style=\"padding: 10px;\">\r\n");
      out.write("	                    <input type=\"number\" id=\"pdtCount\" name=\"pdtCount\" style=\"width: 100%;\">\r\n");
      out.write("	                </td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("				    <td style=\"padding: 10px; text-align: right;\">이미지1 업로드:</td>\r\n");
      out.write("				    <td style=\"padding: 10px;\">\r\n");
      out.write("				        <input type=\"file\" id=\"file1\" name=\"file1\" style=\"width: 100%;\">\r\n");
      out.write("				    </td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				    <td style=\"padding: 10px; text-align: right;\">이미지2 업로드:</td>\r\n");
      out.write("				    <td style=\"padding: 10px;\">\r\n");
      out.write("				        <input type=\"file\" id=\"file2\" name=\"file2\" style=\"width: 100%;\">\r\n");
      out.write("				    </td>\r\n");
      out.write("				</tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	                <td style=\"padding: 10px; text-align: right;\">상품 설명:</td>\r\n");
      out.write("	                <td style=\"padding: 10px;\">\r\n");
      out.write("	                    <textarea id=\"pdtDescription\" name=\"pdtDescription\" style=\"width: 100%; height: 100px;\"></textarea>\r\n");
      out.write("	                </td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	                <td colspan=\"2\" style=\"text-align: center; padding: 10px;\">\r\n");
      out.write("	                    <button type=\"submit\" style=\"padding: 10px 20px; border: 1px solid black; background-color: #ddd\">상품 추가</button>\r\n");
      out.write("	                </td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	        </tbody>\r\n");
      out.write("	    </table>\r\n");
      out.write("	    \r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
